INSERT INTO algorithms (
  id,
  text,
  actionType,
  positive,
  negative,
  onPositive,
  onNegative,
  nextMove,
  tempPlan,
  tempPlanDirP,
  tempPlanDirN,
  conditionalFactor,
  conditionalOperator,
  conditionalValue,
  stateValue,
  label,
  progestogenPossible,
  progestogenPossibleDir,
  delay,
  series,
  active,
  deleted_at,
  created_at,
  updated_at
) VALUES
  (1, 'Are you currently pregnant?', 'bool', 'Yes', 'No', 2, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'pregnant_check', 'false', 'negative', 1, 1, 'Y', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (2, 'Please visit a clinic for pregnancy counselling.', NULL, NULL, NULL, NULL, NULL, NULL, 'Clinic referral', NULL, NULL, NULL, NULL, NULL, NULL, 'pregnant_referral', NULL, NULL, 2, 1, 'Y', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  (3, 'Progestin only pills may be suitable.', NULL, NULL, NULL, NULL, NULL, NULL, 'Progestin Only Pills', NULL, NULL, NULL, NULL, NULL, NULL, 'pop_plan', 'true', 'negative', 3, 1, 'Y', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
