import Joi from 'joi';

export const envValidationSchema = Joi.object({
  APP_ENV: Joi.string().valid('local', 'production', 'test').default('local'),
  PORT: Joi.number().integer().positive().default(3000),
  APP_URL: Joi.string().uri().default('http://localhost:3000'),
  APP_API_DOMAIN: Joi.string().uri().optional(),
  APP_USER_DOMAIN: Joi.string().uri().default('http://localhost:5173'),
  DB_CONNECTION: Joi.string().valid('mysql', 'sqlite').default('sqlite'),
  DB_HOST: Joi.string().optional(),
  DB_PORT: Joi.number().integer().positive().optional(),
  DB_DATABASE: Joi.string().default(':memory:'),
  DB_USERNAME: Joi.string().allow('').optional(),
  DB_PASSWORD: Joi.string().allow('').optional(),
  JWT_SECRET: Joi.string().min(8).default('change-me-secret'),
  JWT_TTL_SECONDS: Joi.number().integer().positive().default(3600),
  DB_SYNCHRONIZE: Joi.boolean().truthy('1', 'true', 'yes').falsy('0', 'false', 'no').default(true),
  AUTO_SEED: Joi.boolean().truthy('1', 'true', 'yes').falsy('0', 'false', 'no').optional(),
  SESSION_SECRET: Joi.string().min(8).default('incharge-session-secret'),
  SESSION_STORE: Joi.string().valid('memory', 'mysql').default('memory'),
  MAIL_ENABLED: Joi.boolean().truthy('1', 'true', 'yes').falsy('0', 'false', 'no').default(false),
  MAIL_HOST: Joi.string().allow('').optional(),
  MAIL_PORT: Joi.number().integer().positive().optional(),
  MAIL_USERNAME: Joi.string().allow('').optional(),
  MAIL_PASSWORD: Joi.string().allow('').optional(),
  MAIL_ENCRYPTION: Joi.string().allow('').optional(),
  PASSWORD_RESET_EXPIRY_MINUTES: Joi.number().integer().positive().default(60),
  EMAIL_VERIFICATION_EXPIRY_MINUTES: Joi.number().integer().positive().default(4320),
});
